---
# Handler to handle common notifications. Handlers are called by other plays.
# # See http://docs.ansible.com/playbooks_intro.html for more information about handlers.
- name: restart ntp
  service: name=ntpd state=restarted

# - name: restart mariadb
#   service: name=mariadb state=restarted

# restart databases
- name: restart db
  service: name=mariadb state=restarted enabled=yes

# restart httpd service
- name: restart httpd
  service: name=httpd state=restarted enabled=yes

# restart sshd service - http://docs.ansible.com/ansible/latest/modules/systemd_module.html#examples
- name: restart sshd
  systemd:
    name: sshd 
    state: reloaded

# - name: restart sshd
#   service: name=sshd state=restarted

# # sshd restart https://github.com/ansible/ansible-modules-core/issues/1533
# - name: restart sshd
#   # shell: systemctl restart sshd
#   # centos 7.5
#   shell: /bin/systemctl restart sshd.service
#   async: 1
#   poll: 0

# # sshd - does not work
# - name: restart sshd
#   service:
#     name: ssh
#     state: restarted

